server:
  port: 8080

eureka:
  client:
   register-with-eureka: false
   fetch-registry: false
   serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: spring-reactive
    hostname: localhost

spring:
  application:
    name: spring-reactive

logging:
  level:
    com.palvair: DEBUG
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF


cxf:
 path : /cxf
 jaxrs:
  component-scan: true
  classes-scan-packages: com.palvair.spring.reactive